# Generated by Django 5.1.6 on 2025-03-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
